name: Test SSH Connection to GCP VM

on:
  push:
    branches: [main]

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Test SSH Connection from GitHub Actions
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          script: "echo 'GitHub Actions SSH works!'"
