name: Deploy to GCP VM

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # STEP A: Build & save Docker image
      - name: Build Docker Image
        run: |
          docker build -t frontend:latest .
          docker save -o oden-frontend.tar frontend:latest

      # STEP B: Write Private Key to 'keyfile'
      - name: Write SSH Keyfile
        run: |
          echo "${{ secrets.GCP_VM_SSH_KEY }}" > keyfile
          chmod 600 keyfile

      # STEP C: scp the tar to VM using 'key_path'
      - name: Transfer Docker Image to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key_path: keyfile    # <--- Use file instead of raw multiline secret
          source: "oden-frontend.tar"
          target: "/home/${{ secrets.GCP_VM_USER }}/"

      # STEP D: ssh into VM to load & run container
      - name: Deploy Container on VM
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key_path: keyfile    # <--- Same approach here
          script: |
            sudo docker stop oden-frontend || true
            sudo docker rm oden-frontend || true
            sudo docker load < /home/${{ secrets.GCP_VM_USER }}/oden-frontend.tar
            sudo docker run -d -p 80:80 --name=oden-frontend frontend:latest
