name: Test SSH Connection

on:
  push:
    branches: [main]

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Manual SSH Test
        run: |
          echo "${{ secrets.GCP_VM_SSH_KEY }}" > keyfile
          chmod 600 keyfile
          ssh -o StrictHostKeyChecking=no -i keyfile ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} "echo 'SSH SUCCESS on ' \$(whoami)@\$(hostname)"
