name: Debug SSH Key Presence

on:
  push:
    branches: [main]

jobs:
  debug-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Debug SSH Key Presence
        run: |
          if [ -z "${{ secrets.GCP_VM_SSH_KEY }}" ]; then
            echo "ERROR: SSH key is empty or missing!"
            exit 1
          else
            echo "SSH Key is present. Length: $(echo "${{ secrets.GCP_VM_SSH_KEY }}" | wc -c) characters."
          fi
