name: Test SSH
on:
  push:
    branches: [main]

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: SSH Test
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          script: |
            echo "SSH SUCCESS on $(whoami)@$(hostname)"
