name: Deploy to GCP VM

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          # 1) Build the Docker image
          docker build -t frontend:latest .
          # 2) Save it to a tar file
          docker save -o oden-frontend.tar frontend:latest

      - name: Write SSH Keyfile
        run: |
          # This step writes your multiline private key into a file named 'keyfile'
          echo "${{ secrets.GCP_VM_SSH_KEY }}" > keyfile
          chmod 600 keyfile

      - name: Transfer Docker Image to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          # IMPORTANT: we use 'key_path: keyfile' instead of 'key:'
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key_path: keyfile
          source: "oden-frontend.tar"
          target: "/home/${{ secrets.GCP_VM_USER }}/"

      - name: Deploy Container on VM
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key_path: keyfile   # again we use 'key_path'
          script: |
            sudo docker stop oden-frontend || true
            sudo docker rm oden-frontend || true
            sudo docker load < /home/${{ secrets.GCP_VM_USER }}/oden-frontend.tar
            sudo docker run -d -p 80:80 --name=oden-frontend frontend:latest
