name: Deploy
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Auth GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Build Docker
        run: |
          docker build -t frontend:latest .
          docker tag frontend:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend
          